cask "amazon-chime"
cask "adobe-acrobat-reader"
cask "discord"
cask "drawio"
cask "jetbrains-toolbox"
cask "microsoft-office"
cask "microsoft-teams"
cask "skype"
cask "skype-for-business"
cask "slack"
cask "tunnelblick"
cask "visual-studio-code"
cask "zoom"

mas "Microsoft Remote Desktop", id: 1295203466
